//import { Raleway } from "next/font/google";
import { Kanit } from "next/font/google";
import "./globals.css";
import HeaderNavBar from "../components/HeaderNavBar";

//const kanit = Kanit({ subsets: ["latin"] });
const kanit = Kanit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: 'font-kanit', 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <HeaderNavBar/>
        {children}
      </body>
    </html>
  );
}
